In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [5]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [6]:
torch.rand(3, 3, 3)

tensor([[[0.8311, 0.7041, 0.2292],
         [0.0233, 0.4201, 0.0880],
         [0.5753, 0.7292, 0.9765]],

        [[0.4505, 0.4606, 0.5302],
         [0.6117, 0.1919, 0.8333],
         [0.7618, 0.8759, 0.9344]],

        [[0.1820, 0.1697, 0.1325],
         [0.0240, 0.0316, 0.9803],
         [0.8908, 0.4336, 0.5960]]])

In [7]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([0., 0., 0.])

In [9]:
ones_like_zeros[:, 0]

tensor([1., 1., 1.])

In [ ]:
x = ones_like_zeros.detach()
print(x)

In [ ]:
x[:, 0] * 5

In [ ]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

In [ ]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)